FROM node:24-slim

WORKDIR /app

# Instala dependências para compilar pacotes nativos e rodar o Chromium do Playwright
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    ca-certificates \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libxkbcommon0 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libgbm1 \
    libasound2 \
    libpangocairo-1.0-0 \
    libpango-1.0-0 \
    libgtk-3-0 \
    libnss3 \
    libx11-xcb1 \
    libxshmfence1 \
    libglu1-mesa \
    wget \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./

# Instala as dependências do Node e do Playwright
RUN npm install
# Instala os navegadores do Playwright
RUN npx playwright install --with-deps

COPY . .

EXPOSE 3333

CMD ["npm", "run", "dev"]
